CREATE TABLE IF NOT EXISTS users (
  tenant_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  role VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (tenant_id, user_id)
);

CREATE TABLE IF NOT EXISTS data_objects (
  tenant_id VARCHAR(128) NOT NULL,
  data_id VARCHAR(128) NOT NULL,
  owner_id VARCHAR(128) NOT NULL,
  algorithm VARCHAR(32) NOT NULL,
  content_key_version INT NOT NULL,
  ciphertext_hash VARCHAR(128) NOT NULL,
  storage_path VARCHAR(512) NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (tenant_id, data_id),
  FOREIGN KEY (tenant_id, owner_id) REFERENCES users(tenant_id, user_id)
);

CREATE TABLE IF NOT EXISTS grants (
  tenant_id VARCHAR(128) NOT NULL,
  grant_id VARCHAR(128) NOT NULL,
  data_id VARCHAR(128) NOT NULL,
  owner_id VARCHAR(128) NOT NULL,
  recipient_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  policy_hash VARCHAR(128) NOT NULL,
  content_key_version INT NOT NULL,
  access_count INT NOT NULL,
  reencrypt_count INT NOT NULL,
  download_count INT NOT NULL,
  decrypt_count INT NOT NULL,
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (tenant_id, grant_id),
  FOREIGN KEY (tenant_id, data_id) REFERENCES data_objects(tenant_id, data_id),
  FOREIGN KEY (tenant_id, owner_id) REFERENCES users(tenant_id, user_id),
  FOREIGN KEY (tenant_id, recipient_id) REFERENCES users(tenant_id, user_id)
);

CREATE TABLE IF NOT EXISTS packages (
  tenant_id VARCHAR(128) NOT NULL,
  package_id VARCHAR(128) NOT NULL,
  grant_id VARCHAR(128) NOT NULL,
  data_id VARCHAR(128) NOT NULL,
  recipient_id VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL,
  content_key_version INT NOT NULL,
  created_at TIMESTAMP NOT NULL,
  PRIMARY KEY (tenant_id, package_id),
  FOREIGN KEY (tenant_id, grant_id) REFERENCES grants(tenant_id, grant_id)
);

CREATE TABLE IF NOT EXISTS aes_gcm_nonces (
  key_fingerprint VARCHAR(128) NOT NULL,
  nonce VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key_fingerprint, nonce)
);

CREATE TABLE IF NOT EXISTS token_revocations (
  tenant_id VARCHAR(128) NOT NULL,
  token_id VARCHAR(128) NOT NULL,
  revoked_at TIMESTAMP NOT NULL,
  reason VARCHAR(256),
  PRIMARY KEY (tenant_id, token_id)
);

CREATE TABLE IF NOT EXISTS audit_events (
  tenant_id VARCHAR(128) NOT NULL,
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id VARCHAR(128) NOT NULL UNIQUE,
  actor VARCHAR(128) NOT NULL,
  action VARCHAR(128) NOT NULL,
  target VARCHAR(256) NOT NULL,
  event_hash VARCHAR(128) NOT NULL,
  previous_hash VARCHAR(128) NOT NULL,
  created_at TIMESTAMP NOT NULL
);
